# SPDX-FileCopyrightText: 2026 Alexey Zhokhov
# SPDX-License-Identifier: Apache-2.0

[package]
name = "termrock-lookbook-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "WASM host adapter for the shared TermRock demo runtime"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
termrock-lookbook = { version = "0.11.0", path = "../termrock-lookbook", default-features = false }
serde_json.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
