// SPDX-FileCopyrightText: 2026 Alexey Zhokhov
// SPDX-License-Identifier: Apache-2.0

mod render;
mod stories;

use std::{
    collections::BTreeSet,
    env, fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;
use termrock::Theme;
use termrock_head::style::RolePalette;

const OLD_REV: &str = "5ff94ee117fd4a1b72fdd0d1b1847815055a93ac";
const SUBSET_COMPONENTS: [&str; 16] = [
    "ActionBar",
    "Backdrop",
    "ChoiceDialog",
    "DetailTable",
    "Dialog",
    "DiffView",
    "HintBar",
    "List",
    "MessageDialog",
    "Panel",
    "Progress",
    "StatusBar",
    "Tabs",
    "TextInput",
    "Toast",
    "Viewport",
];

#[derive(Debug, Deserialize)]
struct HeadStory {
    id: String,
    component: String,
}

#[derive(Debug, PartialEq, Eq)]
struct Partition {
    comparable: Vec<String>,
    uncomparable: Vec<(String, String)>,
}

fn partition(head: &[HeadStory], comparable: &BTreeSet<&str>) -> Partition {
    let mut result = Partition {
        comparable: Vec::new(),
        uncomparable: Vec::new(),
    };
    for story in head
        .iter()
        .filter(|story| SUBSET_COMPONENTS.contains(&story.component.as_str()))
    {
        if comparable.contains(story.id.as_str()) {
            result.comparable.push(story.id.clone());
        } else {
            result
                .uncomparable
                .push((story.id.clone(), story.component.clone()));
        }
    }
    result.uncomparable.sort();
    result
}

fn slug(id: &str) -> String {
    format!("{}.png", id.replace('/', "-"))
}

fn arguments() -> Result<(PathBuf, PathBuf), String> {
    let mut args = env::args().skip(1);
    let mut head_stories = None;
    let mut out = PathBuf::from("out");
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--head-stories" => head_stories = args.next().map(PathBuf::from),
            "--out" => out = args.next().map(PathBuf::from).ok_or("--out needs a path")?,
            _ => return Err(format!("unknown argument: {arg}")),
        }
    }
    Ok((
        head_stories.ok_or("usage: oldrev-harness --head-stories <json> [--out <dir>]")?,
        out,
    ))
}

fn uncomparable_markdown(rows: &[(String, String)], inventory: &Path) -> String {
    let mut output = format!(
        "# Uncomparable HEAD stories\n\nGenerated by `cargo run --locked -- --head-stories {}`.\n\nOld revision: `{OLD_REV}`\n\n",
        inventory.display()
    );
    for (id, component) in rows {
        output.push_str(&format!(
            "- `{id}` ({component}): component exists at 5ff94ee1 but this state has no Old-rev story counterpart and no equivalent public-constructor setup was defined at the pin\n"
        ));
    }
    output
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let (inventory, out) = arguments().map_err(std::io::Error::other)?;
    let head: Vec<HeadStory> = serde_json::from_slice(&fs::read(&inventory)?)?;
    let stories = stories::stories();
    let comparable: BTreeSet<_> = stories.iter().map(|story| story.id).collect();
    let partition = partition(&head, &comparable);
    let filtered: BTreeSet<_> = head
        .iter()
        .filter(|story| SUBSET_COMPONENTS.contains(&story.component.as_str()))
        .map(|story| story.id.as_str())
        .collect();
    let classified: BTreeSet<_> = partition
        .comparable
        .iter()
        .map(String::as_str)
        .chain(partition.uncomparable.iter().map(|(id, _)| id.as_str()))
        .collect();
    if filtered != classified {
        return Err(format!(
            "HEAD subset classification mismatch: filtered={filtered:?}, classified={classified:?}"
        )
        .into());
    }
    if partition.comparable.len() != stories.len() {
        return Err(format!(
            "expected all {} comparable stories at HEAD, found {}",
            stories.len(),
            partition.comparable.len()
        )
        .into());
    }

    fs::create_dir_all(&out)?;
    let theme = Theme::default();
    let palette = RolePalette::default();
    for story in stories {
        let id = story.id;
        let buffer = render::render_story_to_buffer(story, &theme);
        fs::write(
            out.join(slug(id)),
            termrock_raster::render_png(&buffer, &palette)?,
        )?;
    }
    fs::write(
        out.join("uncomparable.md"),
        uncomparable_markdown(&partition.uncomparable, &inventory),
    )?;
    Ok(())
}

fn main() {
    if let Err(error) = run() {
        eprintln!("oldrev-harness: {error}");
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn partition_splits_comparable_and_uncomparable() {
        let fixture: Vec<HeadStory> = serde_json::from_str(
            r#"[
                {"id":"text-input/basic","component":"TextInput"},
                {"id":"text-input/unicode","component":"TextInput"},
                {"id":"table/basic","component":"Table"}
            ]"#,
        )
        .unwrap();
        let comparable = BTreeSet::from(["text-input/unicode"]);
        assert_eq!(
            partition(&fixture, &comparable),
            Partition {
                comparable: vec!["text-input/unicode".into()],
                uncomparable: vec![("text-input/basic".into(), "TextInput".into())],
            }
        );
    }

    #[test]
    fn slug_matches_old_convention() {
        assert_eq!(slug("panel/focused"), "panel-focused.png");
    }
}
