import { readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { frontmatter, list, scalar } from './doc-frontmatter'

type Demo = {
  id: string
  component: string
  interactive: boolean
  interactionKind: string
  hints: string[]
}
type Route = { component: string; slug: string; demo: string }
type Migration = { source: string; kind: string; destination: string }

const root = join(import.meta.dir, '..', '..')
const docs = join(root, 'docs', 'content', 'docs')
const routeManifest = JSON.parse(
  await Bun.file(join(root, 'docs', 'api', 'component-routes.json')).text(),
) as Route[]
const result = Bun.spawnSync(
  ['cargo', 'run', '-q', '-p', 'termrock-lookbook', '--', 'list', '--format', 'json'],
  { cwd: root },
)
if (result.exitCode !== 0) throw new Error(result.stderr.toString())
const catalog = JSON.parse(result.stdout.toString()) as Demo[]
const demos = new Map(catalog.map((entry) => [entry.id, entry]))

if (routeManifest.length !== 165) {
  throw new Error(`canonical route manifest drift: expected 165, got ${routeManifest.length}`)
}
if (new Set(routeManifest.map((entry) => entry.component)).size !== routeManifest.length) {
  throw new Error('duplicate component in canonical route manifest')
}
if (new Set(routeManifest.map((entry) => entry.slug)).size !== routeManifest.length) {
  throw new Error('duplicate slug in canonical route manifest')
}

const api = await Bun.file(join(root, 'docs', 'api', 'public-api.txt')).text()
const publicWidgets = new Set(
  [...api.matchAll(/^impl.*ratatui_core::widgets::(?:widget::Widget|stateful_widget::StatefulWidget) for &?termrock::widgets::([A-Z][A-Za-z0-9_]*)/gm)]
    .map((match) => match[1]!),
)
if (publicWidgets.size !== 135) throw new Error(`public widget inventory drift: ${publicWidgets.size}`)
const routedComponents = new Set(routeManifest.map((entry) => entry.component))
const missingPublic = [...publicWidgets].filter((component) => !routedComponents.has(component))
if (missingPublic.length) throw new Error(`public widgets without canonical page: ${missingPublic.join(', ')}`)

const actualFiles = (await readdir(join(docs, 'components')))
  .filter((name) => name.endsWith('.mdx'))
  .map((name) => name.replace(/\.mdx$/, ''))
  .sort()
const expectedFiles = routeManifest.map((entry) => entry.slug).sort()
if (JSON.stringify(actualFiles) !== JSON.stringify(expectedFiles)) {
  throw new Error('component routes differ from docs/api/component-routes.json')
}

const requiredSections = [
  '## Usage',
  '## Interaction contract',
  '## Stories',
  '## Try it',
  '## State and typed outcomes',
  '## Common mistakes',
  '## Test recipe',
  '## Source and related material',
]
for (const route of routeManifest) {
  const path = join(docs, 'components', `${route.slug}.mdx`)
  const body = await Bun.file(path).text()
  const meta = frontmatter(body)
  const component = scalar(meta, 'component')
  const demoId = scalar(meta, 'demo')
  const interaction = scalar(meta, 'interaction')
  const source = scalar(meta, 'source')
  if (component !== route.component || demoId !== route.demo) {
    throw new Error(`${route.slug}: frontmatter differs from route manifest`)
  }
  const demo = demos.get(route.demo)
  if (!demo) throw new Error(`${route.slug}: unknown demo ${route.demo}`)
  if (interaction !== demo.interactionKind) {
    throw new Error(`${route.slug}: interaction ${interaction} != catalog ${demo.interactionKind}`)
  }
  const actions = list(meta, 'actions')
  for (const hint of demo.hints) {
    if (!actions.includes(hint)) throw new Error(`${route.slug}: missing catalog action ${hint}`)
  }
  if (!demo.interactive && actions.length) {
    throw new Error(`${route.slug}: passive demo claims actions: ${actions.join(', ')}`)
  }
  if (!demo.interactive && body.includes('use keys/click for states')) {
    throw new Error(`${route.slug}: passive demo caption claims unsupported interaction`)
  }
  if (
    demo.interactive
    && (body.includes('honest paint-only preview')
      || body.includes('No actions. This component is passive'))
  ) {
    throw new Error(`${route.slug}: interactive demo still claims paint-only behavior`)
  }
  if (demo.interactive && list(meta, 'expectedOutcomes').length === 0) {
    throw new Error(`${route.slug}: interactive demo has no expected outcome contract`)
  }
  if (!source || !(await Bun.file(join(root, source)).exists())) {
    throw new Error(`${route.slug}: invalid source ${source}`)
  }
  const previews = [...body.matchAll(/<TerminalPreview\s+[^>]*story=["']([^"']+)["']/g)]
  if (previews.length !== 1 || previews[0]?.[1] !== route.demo) {
    throw new Error(`${route.slug}: needs exactly one matching live demo`)
  }
  for (const section of requiredSections) {
    if (!body.includes(section)) throw new Error(`${route.slug}: missing ${section}`)
  }
  if (body.includes('Generated by scripts/gen-component-pages')) {
    throw new Error(`${route.slug}: canonical prose still claims generated ownership`)
  }
}

const migrations = JSON.parse(
  await Bun.file(join(root, 'docs', 'api', 'handbook-route-migration.json')).text(),
) as Migration[]
if (migrations.length !== 84 || new Set(migrations.map((entry) => entry.source)).size !== 84) {
  throw new Error('handbook migration map must classify exactly 84 unique MDX files')
}
if (await Bun.file(join(docs, 'handbook')).exists()) throw new Error('duplicate Handbook directory exists')
for (const migration of migrations) {
  if (!['component', 'pattern', 'concept'].includes(migration.kind)) {
    throw new Error(`${migration.source}: invalid migration kind`)
  }
  const relative = migration.destination.replace(/^\/docs\//, '')
  if (!(await Bun.file(join(docs, `${relative}.mdx`)).exists())) {
    throw new Error(`${migration.source}: missing destination ${migration.destination}`)
  }
}

console.log(`component docs: ${publicWidgets.size}/135 public widget inventory; ${routeManifest.length}/165 canonical routes; 84/84 Handbook migrations`)
