import { componentDocs } from './component-docs'
import { componentSlug } from './component-doc-utils'

interface Story {
  readonly id: string
  readonly title: string
  readonly component: string
}

type Contract = Record<'keyboard' | 'mouse' | 'focus' | 'nonColor' | 'unicode' | 'narrowTerminal', string>

const root = `${import.meta.dir}/../..`
const outputDir = `${root}/docs/content/docs/components`
const check = Bun.argv.slice(2).includes('--check')
const componentPattern = /^impl.*ratatui_core::widgets::(?:widget::Widget|stateful_widget::StatefulWidget) for &?termrock::widgets::([A-Z][A-Za-z0-9_]*)/

function escapeTable(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ')
}

async function writeOrCheck(path: string, expected: string): Promise<void> {
  if (check) {
    const actual = Bun.file(path)
    if (!(await actual.exists()) || (await actual.text()) !== expected) {
      throw new Error(`stale generated component documentation: ${path}`)
    }
    return
  }
  await Bun.write(path, expected)
}

const api = await Bun.file(`${root}/docs/api/public-api.txt`).text()
const components = [...new Set(api.split('\n').flatMap((line) => line.match(componentPattern)?.[1] ?? []))].sort()
if (components.length === 0) throw new Error('public API report contains no canonical widgets')

const authored = Object.keys(componentDocs).sort()
const missingAuthored = components.filter((component) => !authored.includes(component))
const staleAuthored = authored.filter((component) => !components.includes(component))
if (missingAuthored.length || staleAuthored.length) {
  throw new Error(`authored component docs mismatch; missing: ${missingAuthored.join(', ') || 'none'}; stale: ${staleAuthored.join(', ') || 'none'}`)
}

const contracts = JSON.parse(await Bun.file(`${root}/docs/api/component-contracts.json`).text()) as Record<string, Contract>
const storyResult = Bun.spawnSync(
  ['cargo', 'run', '-q', '-p', 'termrock-lookbook', '--', 'list', '--format', 'json'],
  { cwd: root },
)
if (storyResult.exitCode !== 0) throw new Error(storyResult.stderr.toString())
const stories = (JSON.parse(storyResult.stdout.toString()) as Story[]).toSorted((a, b) => a.id.localeCompare(b.id))

const axes: ReadonlyArray<readonly [keyof Contract, string]> = [
  ['keyboard', 'Keyboard'],
  ['mouse', 'Mouse'],
  ['focus', 'Focus'],
  ['nonColor', 'Non-color cues'],
  ['unicode', 'Unicode'],
  ['narrowTerminal', 'Narrow terminal'],
]

for (const component of components) {
  const authoredDoc = componentDocs[component as keyof typeof componentDocs]
  const contract = contracts[component]
  const componentStories = stories.filter((story) => story.component === component)
  if (!contract) throw new Error(`${component} has no interaction contract`)
  const primary = componentStories.find((story) => story.id === authoredDoc.primaryStory)
  if (!primary) throw new Error(`${component} primary story is missing: ${authoredDoc.primaryStory}`)
  const contractRows = axes.map(([key, label]) => `| ${label} | ${contract[key]} |`).join('\n')
  const storyRows = componentStories
    .map((story) => `- \`${story.id}\` — ${escapeTable(story.title)}`)
    .join('\n')
  const page = `---
title: ${component}
description: ${authoredDoc.description}
---

{/* Generated by scripts/gen-component-pages.ts. Edit component-docs.ts instead. */}

![${component} — ${escapeTable(primary.title)}](/component-previews/${primary.id.replaceAll('/', '-')}.svg)

## Usage

\`\`\`rust
${authoredDoc.usage}
\`\`\`

## Interaction contract

| Axis | Status |
|---|---|
${contractRows}

## Stories

${storyRows}
`
  await writeOrCheck(`${outputDir}/${componentSlug(component)}.mdx`, page)
}

const expectedFiles = new Set(components.map((component) => `${componentSlug(component)}.mdx`))
if (await Bun.file(outputDir).exists()) {
  for await (const name of new Bun.Glob('*.mdx').scan({ cwd: outputDir })) {
    if (!expectedFiles.has(name)) {
      if (check) throw new Error(`stale generated component page: ${outputDir}/${name}`)
      await Bun.file(`${outputDir}/${name}`).delete()
    }
  }
}

const meta = `${JSON.stringify({
  title: 'Components',
  pagesIndex: '../components',
  defaultOpen: true,
  pages: components.map(componentSlug),
}, null, 2)}\n`
await writeOrCheck(`${outputDir}/meta.json`, meta)

const indexRows = components
  .map((component) => `| [${component}](./${componentSlug(component)}) | ${escapeTable(componentDocs[component as keyof typeof componentDocs].description)} |`)
  .join('\n')
const index = `---
title: Components
description: Product-neutral terminal building blocks with explicit interaction contracts.
---

TermRock components accept consumer-owned wording and domain state while owning reusable terminal rendering, focus behavior, hit geometry, Unicode safety, narrow-terminal behavior, and non-color cues.

| Component | Purpose |
|---|---|
${indexRows}

## Shared guarantees

All widgets tolerate empty and narrow rectangles. Disabled items are not hit targets. Mouse regions derive from painted geometry. Stable identities survive filtering and reordering. Consumers own effects, navigation policy, and dialog stacking.

Panel and dialog borders use one plain, single-line glyph set. Focus is communicated through the semantic \`Role::BorderFocused\` theme role; inactive containers use \`Role::Border\`.
`
await writeOrCheck(`${root}/docs/content/docs/components.mdx`, index)

console.log(`${check ? 'verified' : 'generated'} ${components.length} component reference pages`)
