import { componentDocs } from './component-docs'
import { componentSlug } from './component-doc-utils'

interface Story {
  readonly id: string
  readonly title: string
  readonly component: string
}

type Contract = Record<'keyboard' | 'mouse' | 'focus' | 'nonColor' | 'unicode' | 'narrowTerminal', string>

const root = `${import.meta.dir}/../..`
const outputDir = `${root}/docs/content/docs/components`
const check = Bun.argv.slice(2).includes('--check')
const componentPattern = /^impl.*ratatui_core::widgets::(?:widget::Widget|stateful_widget::StatefulWidget) for &?termrock::widgets::([A-Z][A-Za-z0-9_]*)/

function escapeTable(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ')
}

function escapeAttr(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('"', '&quot;')
}

/** Infer a short axis/role label from story id for the stories table. */
function storyFocus(storyId: string, isPrimary: boolean): string {
  if (isPrimary) return '**Primary (live preview)**'
  const tail = storyId.split('/').pop() ?? storyId
  const labels: Record<string, string> = {
    narrow: 'Narrow terminal',
    unicode: 'Unicode / wide glyphs',
    ascii: 'ASCII / low capability',
    tiny: 'Tiny viewport',
    empty: 'Empty state',
    loading: 'Loading state',
    disabled: 'Disabled',
    multi: 'Multi-select',
    search: 'Search / filter',
    basic: 'Baseline layout',
    compact: 'Compact density',
    comfortable: 'Comfortable density',
    overflow: 'Overflow',
    open: 'Open / expanded',
    closed: 'Closed',
    error: 'Error',
    failed: 'Failed',
    interactive: 'Interactive',
  }
  return labels[tail] ?? escapeTable(tail.replaceAll('-', ' '))
}

async function writeOrCheck(path: string, expected: string): Promise<void> {
  if (check) {
    const actual = Bun.file(path)
    if (!(await actual.exists()) || (await actual.text()) !== expected) {
      throw new Error(`stale generated component documentation: ${path}`)
    }
    return
  }
  await Bun.write(path, expected)
}

const api = await Bun.file(`${root}/docs/api/public-api.txt`).text()
const components = [...new Set(api.split('\n').flatMap((line) => line.match(componentPattern)?.[1] ?? []))].sort()
if (components.length === 0) throw new Error('public API report contains no canonical widgets')

const authored = Object.keys(componentDocs).sort()
const missingAuthored = components.filter((component) => !authored.includes(component))
const staleAuthored = authored.filter((component) => !components.includes(component))
if (missingAuthored.length || staleAuthored.length) {
  throw new Error(`authored component docs mismatch; missing: ${missingAuthored.join(', ') || 'none'}; stale: ${staleAuthored.join(', ') || 'none'}`)
}

const contracts = JSON.parse(await Bun.file(`${root}/docs/api/component-contracts.json`).text()) as Record<string, Contract>
const storyResult = Bun.spawnSync(
  ['cargo', 'run', '-q', '-p', 'termrock-lookbook', '--', 'list', '--format', 'json'],
  { cwd: root },
)
if (storyResult.exitCode !== 0) throw new Error(storyResult.stderr.toString())
const stories = (JSON.parse(storyResult.stdout.toString()) as Story[]).toSorted((a, b) => a.id.localeCompare(b.id))

const axes: ReadonlyArray<readonly [keyof Contract, string]> = [
  ['keyboard', 'Keyboard'],
  ['mouse', 'Mouse'],
  ['focus', 'Focus'],
  ['nonColor', 'Non-color cues'],
  ['unicode', 'Unicode'],
  ['narrowTerminal', 'Narrow terminal'],
]

for (const component of components) {
  const authoredDoc = componentDocs[component as keyof typeof componentDocs]
  const contract = contracts[component]
  const componentStories = stories.filter((story) => story.component === component)
  if (!contract) throw new Error(`${component} has no interaction contract`)
  const primary = componentStories.find((story) => story.id === authoredDoc.primaryStory)
  if (!primary) throw new Error(`${component} primary story is missing: ${authoredDoc.primaryStory}`)
  const contractRows = axes.map(([key, label]) => `| ${label} | ${contract[key]} |`).join('\n')

  // One interactive Ghostty surface — multi-state lives in pack steps, not N embeds.
  const caption = escapeAttr(
    `${component} · ${primary.title} — focus surface; use keys/click for states`,
  )
  const previewBlock = `<TerminalPreview story="${primary.id}" interactive caption="${caption}" />
`

  // Stories table: variants documented, not re-embedded (SVG-era gallery replaced).
  const orderedStories = [
    primary,
    ...componentStories.filter((story) => story.id !== primary.id),
  ]
  const storyTableRows = orderedStories
    .map((story) => {
      const focus = storyFocus(story.id, story.id === primary.id)
      return `| \`${story.id}\` | ${escapeTable(story.title)} | ${focus} |`
    })
    .join('\n')

  const page = `---
title: ${component}
description: '${authoredDoc.description.replaceAll("'", "''")}'
---

{/* Generated by scripts/gen-component-pages.ts. Edit component-docs.ts instead. */}

## Live terminal (Ghostty-class)

One focused interactive surface — the same TermRock paint path as the lookbook.
**States, narrow, unicode, and transitions live in this preview** (↑↓ / ←→, j/k,
click, Home/End; host resize remaps cols×rows). Other lookbook stories are listed
in the table below — not as extra screens.

${previewBlock}
## Usage

\`\`\`rust
${authoredDoc.usage}
\`\`\`

## Interaction contract

| Axis | Status |
|---|---|
${contractRows}

## Stories

Lookbook coverage for this component. Only the **primary** story is embedded above;
use the interactive preview (and Studio lookbook) to explore transitions instead of
a static multi-image gallery.

| Story | Title | Focus |
|---|---|---|
${storyTableRows}
`
  await writeOrCheck(`${outputDir}/${componentSlug(component)}.mdx`, page)
}

const expectedFiles = new Set(components.map((component) => `${componentSlug(component)}.mdx`))
if (await Bun.file(outputDir).exists()) {
  for await (const name of new Bun.Glob('*.mdx').scan({ cwd: outputDir })) {
    if (expectedFiles.has(name)) continue
    // Hand-authored composite pages (not in Widget-impl inventory) may remain if they
    // already satisfy Ghostty-one-focus rules; catalog check enforces that.
    // Do not delete unknown pages here — check-catalog owns policy.
  }
}

const meta = `${JSON.stringify({
  title: 'Components',
  pagesIndex: '../components',
  defaultOpen: true,
  pages: components.map(componentSlug),
}, null, 2)}\n`
await writeOrCheck(`${outputDir}/meta.json`, meta)

const indexRows = components
  .map((component) => `| [${component}](./${componentSlug(component)}) | ${escapeTable(componentDocs[component as keyof typeof componentDocs].description)} |`)
  .join('\n')
const index = `---
title: Components
description: Product-neutral terminal building blocks with explicit interaction contracts.
---

TermRock components accept consumer-owned wording and domain state while owning reusable terminal rendering, focus behavior, hit geometry, Unicode safety, narrow-terminal behavior, and non-color cues.

Each component page embeds **one** Ghostty-class [\`TerminalPreview\`](/docs) (primary
lookbook story). Additional variants are a **stories table** — interactivity replaces
the old multi-SVG state gallery. SVG snapshots are not used.

| Component | Purpose |
|---|---|
${indexRows}

## Shared guarantees

All widgets tolerate empty and narrow rectangles. Disabled items are not hit targets. Mouse regions derive from painted geometry. Stable identities survive filtering and reordering. Consumers own effects, navigation policy, and dialog stacking.

Panel and dialog borders use one plain, single-line glyph set. Focus is communicated through the semantic \`Role::BorderFocused\` theme role; inactive containers use \`Role::Border\`.
`
await writeOrCheck(`${root}/docs/content/docs/components.mdx`, index)

console.log(
  `${check ? 'verified' : 'generated'} ${components.length} component pages (one Ghostty focus + stories table)`,
)
