import { join } from 'node:path'
import { contractSchemaSource, loadCatalog } from './catalog-data'

const root = join(import.meta.dir, '..', '..')
const output = join(root, 'docs', 'src', 'generated', 'catalog.ts')
const catalog = await loadCatalog()
const serialized = [
  '// Generated by docs/scripts/generate-catalog.ts. Do not edit.',
  '',
  `export const catalogComponentFamilies = ${JSON.stringify(catalog.componentFamilies, null, 2)} as const`,
  '',
  `export const catalogPatternFamilies = ${JSON.stringify(catalog.patternFamilies, null, 2)} as const`,
  '',
  `export const catalogComponents = ${JSON.stringify(catalog.components, null, 2)} as const`,
  '',
  `export const catalogPatterns = ${JSON.stringify(catalog.patterns, null, 2)} as const`,
  '',
  'export const catalogEntries = [...catalogComponents, ...catalogPatterns] as const',
  '',
].join('\n')
const componentMeta = `${JSON.stringify({
  title: 'Components',
  pagesIndex: '../components',
  defaultOpen: false,
  pages: catalog.components.map((entry) => entry.slug),
}, null, 2)}\n`
const patternMeta = `${JSON.stringify({
  title: 'Application patterns',
  pagesIndex: '../patterns',
  defaultOpen: false,
  pages: catalog.patterns.map((entry) => entry.slug),
}, null, 2)}\n`
const outputs = [
  { path: output, source: serialized },
  {
    path: join(root, 'docs', 'api', 'component-contract.schema.json'),
    source: contractSchemaSource(),
  },
  { path: join(root, 'docs', 'content', 'docs', 'components', 'meta.json'), source: componentMeta },
  { path: join(root, 'docs', 'content', 'docs', 'patterns', 'meta.json'), source: patternMeta },
] as const

if (process.argv.includes('--check')) {
  for (const generated of outputs) {
    const current = await Bun.file(generated.path).text().catch(() => '')
    if (current !== generated.source) throw new Error(`${generated.path} is stale; run bun run generate:catalog`)
  }
} else {
  for (const generated of outputs) await Bun.write(generated.path, generated.source)
}

console.log(`${catalog.components.length} components; ${catalog.patterns.length} patterns`)
